version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=eu-west-2
      - DEBUG=1
      - SERVICES=dynamodb,lambda
    ports:
      - '4563-4599:4563-4599'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"     # If it doesn't work, try: - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"